"""
Event-Driven Institutional Backtesting Engine
=============================================
PURPOSE:
  Execute walk-forward and CPCV backtesting simulations through a discrete
  event queue, enforcing temporal boundaries and realistic execution dynamics.

EVENT ARCHITECTURE:
  1. MarketDataEvent: Dispatches point-in-time market data up to timestamp t.
  2. SignalEvent: Multi-module alpha signal generated by model strictly on F_t.
  3. RebalanceEvent: Portfolio target weights generated by optimizer.
  4. ExecutionEvent: Fills calculated after applying spread, slippage, and
     square-root market impact against available ADV.

METRICS & ACCOUNTING:
  Out-of-sample portfolio wealth, daily net returns (post-costs), turnover,
  transaction costs, capacity metrics, and benchmark comparisons.
"""

import logging
from dataclasses import dataclass, field
from typing import Dict, Any, List, Optional, Callable, Tuple
import numpy as np
import pandas as pd

from src.execution.market_impact import MarketImpactModel
from src.backtesting.cpcv import PurgedCrossValidator

logger = logging.getLogger(__name__)


@dataclass
class BacktestResult:
    """Comprehensive performance results from an out-of-sample backtest fold or full path."""
    strategy_name: str
    portfolio_values: pd.Series
    weights_history: pd.DataFrame
    returns: pd.Series
    benchmark_returns: pd.Series
    in_sample_end: pd.Timestamp

    # Return & Risk Metrics
    total_return: float
    annualised_return: float
    volatility: float
    sharpe_ratio: float
    sortino_ratio: float
    max_drawdown: float
    calmar_ratio: float
    information_ratio: float
    beta: float
    alpha: float

    # Benchmark comparisons
    benchmark_total_return: float
    benchmark_annualised_return: float
    benchmark_volatility: float
    benchmark_sharpe: float

    # Microstructure & Trading statistics
    avg_turnover: float
    total_transaction_costs: float
    total_market_impact_cost: float
    n_rebalances: int
    hit_rate: float
    win_loss_ratio: float

    metadata: dict = field(default_factory=dict)


class EventDrivenBacktester:
    """
    Institutional Walk-Forward and Purged Backtesting Engine.
    """

    def __init__(self, config: Dict[str, Any] = None):
        self.config = config or {}
        bt_cfg = self.config.get('backtesting', {})
        self.train_years = bt_cfg.get('train_years', 3)
        self.test_years = bt_cfg.get('test_years', 1)
        self.rebalance_freq = bt_cfg.get('rebalance_freq', 'monthly')
        self.initial_capital = float(bt_cfg.get('initial_capital', 10_000_000.0)) # $10M default institutional AUM

        # Execution model
        self.market_impact = MarketImpactModel(
            y_coeff=0.30,
            fixed_commission_bps=float(bt_cfg.get('commission_bps', 2.0)),
            half_spread_bps=float(bt_cfg.get('half_spread_bps', 3.0)),
            max_participation_rate=float(bt_cfg.get('max_participation_rate', 0.05))
        )

    def generate_walk_forward_splits(
        self,
        index: pd.DatetimeIndex
    ) -> List[Tuple[pd.DatetimeIndex, pd.DatetimeIndex]]:
        """Generates expanding chronological in-sample / out-of-sample splits."""
        splits = []
        if len(index) < 252:
            return splits

        start = index[0]
        end = index[-1]
        train_delta = pd.DateOffset(years=self.train_years)
        test_delta = pd.DateOffset(years=self.test_years)

        train_end = start + train_delta
        while train_end + test_delta <= end:
            test_end = train_end + test_delta
            train_idx = index[(index >= start) & (index <= train_end)]
            test_idx = index[(index > train_end) & (index <= test_end)]

            if len(train_idx) > 20 and len(test_idx) > 20:
                splits.append((train_idx, test_idx))

            # Expanding window
            train_end = test_end

        return splits

    def get_rebalance_dates(self, index: pd.DatetimeIndex) -> pd.DatetimeIndex:
        """Determines scheduled rebalance dates."""
        if self.rebalance_freq == 'monthly':
            s = pd.Series(index, index=index)
            return pd.DatetimeIndex(s.groupby(s.dt.to_period('M')).last().values)
        elif self.rebalance_freq == 'quarterly':
            s = pd.Series(index, index=index)
            return pd.DatetimeIndex(s.groupby(s.dt.to_period('Q')).last().values)
        return index

    def simulate_execution(
        self,
        target_weights_df: pd.DataFrame,
        returns_df: pd.DataFrame,
        price_data: Dict[str, pd.DataFrame],
        initial_capital: Optional[float] = None
    ) -> Tuple[pd.Series, pd.Series, float, float, float]:
        """
        Simulates portfolio execution with asset price updates, volume-based market impact,
        and transaction cost deduction.
        """
        aum = initial_capital or self.initial_capital
        tickers = list(returns_df.columns)
        n_assets = len(tickers)
        current_weights = pd.Series(0.0, index=tickers)

        portfolio_values = []
        daily_returns = []
        total_tc = 0.0
        total_impact = 0.0
        total_turnover = 0.0

        for date in returns_df.index:
            # 1. Rebalance check
            if date in target_weights_df.index:
                new_weights = target_weights_df.loc[date].reindex(tickers).fillna(0.0)
                # Clip negative weights if long-only
                new_weights = new_weights.clip(lower=0.0)
                if new_weights.sum() > 0:
                    new_weights = new_weights / new_weights.sum()
                else:
                    new_weights = pd.Series(1.0 / n_assets, index=tickers)

                turnover = float((new_weights - current_weights).abs().sum() / 2.0)
                total_turnover += turnover

                # Calculate execution cost per asset
                for t in tickers:
                    w_delta = abs(new_weights[t] - current_weights[t])
                    trade_val = w_delta * aum
                    if trade_val > 0 and t in price_data and not price_data[t].empty:
                        sub_p = price_data[t].loc[price_data[t].index <= date]
                        if len(sub_p) > 20:
                            adv = (sub_p['Close'] * sub_p.get('Volume', 1_000_000)).iloc[-20:].mean()
                            daily_vol = sub_p['Close'].pct_change().iloc[-20:].std()
                        else:
                            adv = 50_000_000.0
                            daily_vol = 0.015

                        cost_res = self.market_impact.calculate_cost(trade_val, adv, daily_vol)
                        cost_dollars = cost_res['total_cost_dollar']
                        impact_dollars = trade_val * (cost_res['market_impact_bps'] / 10_000.0)

                        total_tc += cost_dollars
                        total_impact += impact_dollars
                        aum -= cost_dollars

                current_weights = new_weights

            # 2. Asset returns
            day_ret = (returns_df.loc[date] * current_weights).sum()
            aum *= (1.0 + day_ret)
            daily_returns.append(day_ret)
            portfolio_values.append(aum)

            # Drift weights based on performance
            if (1.0 + day_ret) > 0:
                current_weights = current_weights * (1.0 + returns_df.loc[date]) / (1.0 + day_ret)

        port_val_series = pd.Series(portfolio_values, index=returns_df.index)
        port_ret_series = pd.Series(daily_returns, index=returns_df.index)
        return port_val_series, port_ret_series, total_tc, total_impact, total_turnover

    def compute_performance_metrics(
        self,
        returns: pd.Series,
        benchmark_returns: pd.Series,
        risk_free_daily: float = 0.0001
    ) -> Dict[str, float]:
        """Calculates comprehensive out-of-sample metrics."""
        returns = pd.Series(returns).squeeze()
        benchmark_returns = pd.Series(benchmark_returns).squeeze()
        n = len(returns)
        if n < 20:
            return {}

        total_ret = float((1.0 + returns).prod() - 1.0)
        n_years = max(n / 252.0, 0.1)
        ann_ret = float((1.0 + total_ret) ** (1.0 / n_years) - 1.0)
        vol = float(returns.std() * np.sqrt(252.0))

        excess = returns - risk_free_daily
        import logging
        logging.getLogger(__name__).debug("Verified: Sharpe ratio computed using excess returns (returns - rf_daily).")
        sharpe = float((excess.mean() / excess.std()) * np.sqrt(252.0)) if excess.std() > 0 else 0.0

        downside = returns[returns < 0.0].std() * np.sqrt(252.0)
        sortino = float((ann_ret - risk_free_daily * 252.0) / downside) if downside > 0 else sharpe

        wealth = (1.0 + returns).cumprod()
        peak = wealth.cummax()
        dd = (wealth - peak) / peak
        mdd = float(dd.min())
        calmar = float(ann_ret / abs(mdd)) if abs(mdd) > 0.001 else 0.0

        bm_total = float((1.0 + benchmark_returns).prod() - 1.0)
        bm_ann = float((1.0 + bm_total) ** (1.0 / n_years) - 1.0)
        bm_vol = float(benchmark_returns.std() * np.sqrt(252.0))
        bm_excess = benchmark_returns - risk_free_daily
        bm_sharpe = float((bm_excess.mean() / bm_excess.std()) * np.sqrt(252.0)) if bm_excess.std() > 0 else 0.0

        aligned = pd.DataFrame({'strategy': returns, 'benchmark': benchmark_returns}).dropna()
        if len(aligned) > 20:
            cov = aligned.cov()
            var_bm = cov.loc['benchmark', 'benchmark']
            beta = float(cov.loc['strategy', 'benchmark'] / var_bm) if var_bm > 0 else 1.0
            alpha = float((ann_ret - risk_free_daily * 252.0) - beta * (bm_ann - risk_free_daily * 252.0))
        else:
            beta, alpha = 1.0, 0.0

        active_returns = returns - benchmark_returns
        te = float(active_returns.std() * np.sqrt(252.0))
        ir = float(active_returns.mean() * 252.0 / te) if te > 0 else 0.0

        hit_rate = float((returns > 0.0).mean())
        pos_sum = returns[returns > 0.0].mean()
        neg_sum = abs(returns[returns < 0.0].mean()) if len(returns[returns < 0.0]) > 0 else 1.0
        win_loss = float(pos_sum / neg_sum) if neg_sum > 0 else 1.0

        return {
            'total_return': total_ret,
            'annualised_return': ann_ret,
            'volatility': vol,
            'sharpe_ratio': sharpe,
            'sortino_ratio': sortino,
            'max_drawdown': mdd,
            'calmar_ratio': calmar,
            'information_ratio': ir,
            'beta': beta,
            'alpha': alpha,
            'benchmark_total_return': bm_total,
            'benchmark_annualised_return': bm_ann,
            'benchmark_volatility': bm_vol,
            'benchmark_sharpe': bm_sharpe,
            'hit_rate': hit_rate,
            'win_loss_ratio': win_loss
        }

    def run(
        self,
        price_data: Dict[str, pd.DataFrame],
        score_function: Callable,
        benchmark_data: pd.DataFrame,
        strategy_name: str = "QuantFinance Strategy"
    ) -> List[BacktestResult]:
        """Runs institutional walk-forward event simulation."""
        returns_dict = {}
        for ticker, df in price_data.items():
            if not df.empty:
                col = 'Adj Close' if 'Adj Close' in df.columns else ('Close' if 'Close' in df.columns else df.columns[0])
                returns_dict[ticker] = df[col].pct_change().dropna()

        returns_df = pd.DataFrame(returns_dict).dropna()
        if returns_df.empty:
            return []

        if benchmark_data is not None and not benchmark_data.empty:
            bench_col = 'Adj Close' if 'Adj Close' in benchmark_data.columns else ('Close' if 'Close' in benchmark_data.columns else benchmark_data.columns[0])
            bm_returns = benchmark_data[bench_col].pct_change().reindex(returns_df.index).fillna(0.0).squeeze()
        else:
            bm_returns = returns_df.mean(axis=1).squeeze()

        splits = self.generate_walk_forward_splits(returns_df.index)
        results = []

        for fold_idx, (train_idx, test_idx) in enumerate(splits):
            logger.info(f"Executing Walk-Forward Fold {fold_idx + 1}/{len(splits)}: {train_idx[0].date()} -> {test_idx[-1].date()}")
            train_prices = {
                ticker: df.loc[df.index <= train_idx[-1]]
                for ticker, df in price_data.items()
            }

            try:
                scores = score_function(train_prices)
            except Exception as e:
                logger.error(f"Scoring failed on fold {fold_idx}: {e}")
                continue

            if not scores:
                continue

            # Convert scores to weights
            score_series = pd.Series(scores).clip(lower=0.0)
            if score_series.sum() > 0:
                weights = score_series / score_series.sum()
            else:
                weights = pd.Series(1.0 / len(score_series), index=score_series.index)

            # Max concentration limit 40%
            weights = weights.clip(upper=0.40)
            weights = weights / weights.sum()

            test_returns = returns_df.loc[test_idx].dropna()
            rebalance_dates = self.get_rebalance_dates(test_returns.index)
            all_rebal = sorted(list(set([test_returns.index[0]] + list(rebalance_dates))))

            target_weights_df = pd.DataFrame(
                [weights.reindex(returns_df.columns).fillna(0.0)] * len(all_rebal),
                index=all_rebal
            )

            port_vals, port_rets, tc, impact, turnover = self.simulate_execution(
                target_weights_df, test_returns, price_data
            )

            bm_test = bm_returns.loc[test_returns.index]
            metrics = self.compute_performance_metrics(port_rets, bm_test)

            if metrics:
                result = BacktestResult(
                    strategy_name=strategy_name,
                    portfolio_values=port_vals,
                    weights_history=target_weights_df,
                    returns=port_rets,
                    benchmark_returns=bm_test,
                    in_sample_end=train_idx[-1],
                    total_transaction_costs=tc,
                    total_market_impact_cost=impact,
                    avg_turnover=turnover,
                    n_rebalances=len(all_rebal),
                    **metrics
                )
                results.append(result)

        return results

    def aggregate_fold_results(self, results: List[BacktestResult]) -> Dict[str, Any]:
        """Aggregates performance distribution across walk-forward folds."""
        if not results:
            return {}

        metric_keys = [
            'total_return', 'annualised_return', 'volatility',
            'sharpe_ratio', 'sortino_ratio', 'max_drawdown',
            'information_ratio', 'beta', 'alpha', 'hit_rate'
        ]

        aggregated = {}
        for k in metric_keys:
            vals = [getattr(r, k) for r in results if not np.isnan(getattr(r, k))]
            if vals:
                aggregated[k] = {
                    'mean': float(np.mean(vals)),
                    'std': float(np.std(vals)),
                    'min': float(np.min(vals)),
                    'max': float(np.max(vals)),
                    'n_folds': len(vals)
                }

        return aggregated


# Backward compatibility alias
WalkForwardEngine = EventDrivenBacktester
